### ISSUE TITLE
laser scanner requires polygon object

### ISSUE THREAD

**Issue by hstarmans** [cihologramas/pyoptools#95]
Hey all,

I am planning to model a prism laser scanner using this software.
Two remarks;

So far I had to implement a polygon object;
```python
from numpy import pi
import numpy as np

from pyoptools.raytrace.component import Component 
from pyoptools.raytrace.mat_lib import Material
from pyoptools.raytrace.surface import Plane
from pyoptools.raytrace.shape import Rectangular, Triangular


class Polygon(Component):
    '''Class to define a polygon prism
    
    This class defines a component containing a glass polygon
    
    sides        -- number of sides
    height       -- height of polygon
    inner radius -- inner radius of polygon    
    '''  
    def __init__(self, sides=3, height=3, inner_radius=10, **traits):
        if sides < 3:
            raise Exception("Polygon should have at least 3 sides.")
        internal_angle = (sides-2)*180/sides
        side_length = 2*inner_radius*np.tan(np.pi/sides) 
        Component.__init__(self,**traits)
        # create a side base shape
        side = Plane(shape=Rectangular(size=(side_length, height)))
        for i in range(sides):
            angle = 2*pi/sides*i
            center = inner_radius*np.array([np.cos(angle), np.sin(angle)])
            self.surflist[f"S{i}"]= (side, (center[0], center[1], 0),(pi/2, 0, angle+pi/2))#angle))
        # create a top/bottom base shape
        triangle = Plane(shape=Triangular(((0,0),(-inner_radius,-side_length/2), (-inner_radius,side_length/2))))
        for i in ['bottom', 'height']:
            surface = len(self.surflist)
            if i == 'bottom':
                offset = -height/2
            else:
                offset = height/2
            for i in range(sides):
                angle = 2*pi/sides*i
                if sides % 2:
                    offset = 2*pi/(sides*2)
                else:
                    offset = 0
                self.surflist[f"S{i+surface}"]= (triangle,(0, 0, offset),(0, 0,angle+offset))
p = Polygon()
from pyoptools.all import Plot3D
Plot3D(p,center=(0,0,0),size=(120,120),rot=[(0,0,0)],scale=6)    
```
Shall I add a request for this into the library?

The laser scanner is described in Freecad, see [video](https://youtu.be/jhr6iEazbQk)
Here you see a video of the prism scanner in [action](https://youtu.be/6PEZtsm7FvE).

Note, that I tested the tutorial and could it get it working but the tutorial is partly broken.
issues i could find are;

- pi is not defined at the start, so needed from math import pi
- many materials use invalid names "SK5" gives error, but "N-SK5" gives no error
- a component requested from Edmund is not defined
- had to replace Edmund component "45113" with "45117" as 45113 cannot be found in library

**Comment by ramezquitao** [comment]
Yes please, add a request to add the polygon.  About the material, the refraction index database was taken from https://refractiveindex.info . In this database N-SK5 is defined but SK5 is not. To solve this issue I have added a  file "pyoptools/raytrace/mat_lib/data/aliases.cfg" where name aliases to the materials can be added. I have not added the SK5 material yet, but you can easily add it to your installation by modifying this file. If you send me a list of other materials you have identified to have an "alias" issue, I can make a commit with all the corrections.

**Comment by ramezquitao** [comment]
One question, did you use assembly4 together with pyoptools? If so, can you elaborate about the process? I'm using a2plus for my assemblies because last time I tested Assembly4 it broke the interaction with pyoptools.

**Comment by ramezquitao** [comment]
I just checked again, and The SF5 indeed exists. It is located in the hikary catalog

**Comment by hstarmans** [comment]
At the moment, I use assembly 4. I build a custom work bench, see [freecad_hexastorm](https://github.com/hstarmans/freecad_hexastorm). This work bench has been partly based upon your code.
I have looked into your company a bit, see my blog on [hackaday](https://hackaday.io/project/21933-open-hardware-fast-high-resolution-laser/log/194103-holographic-imaging). It also includes a render of my current simulation in FreeCad.
Do you use laser scanning at a resolution of 1 micron and a line speed of 1.54 m/s ?
The optical design can be found [here](https://github.com/hstarmans/opticaldesign).

**Comment by ramezquitao** [comment]
Yes, the objects in pyOpTools are not really related to FreeCAD. The idea behind pyOpTools is to create an engine to perform the optical calculations unrelated from any kind of GUI (this may change in to the future). Maybe you already know, but we have been also developing an workbench for FreeCAD ( https://github.com/cihologramas/freecad-pyoptools ) this is still a work in progress, but it has allowed us to "digitally" build some optical systems and check they perform as expected by simulation, and then  to use the exact position of the optics to place the holders and make the mechanical design. Initially we used to export the STEP of the optics and use another CAD software, but I'm trying to migrate everything to FreeCAD and this is what I have used A2plus for. I have not used assembly 4 because I have not found a good workflow where I can change the optics, and migrate that changes to the final assembly. With A2plus is almost direct. 
Regarding your question about our machine, we are scanning with a laser and a line speed that could go up to 2 or maybe 2.2 m/s at 1 um resolution. But we don't use mechanical scanners, we have found them to be too slow. Right now we about to present a new machine where we expect to get about  2 times the printing speed with an address grid  resolution of 0.1 um , but this machine will use a completely different technology.

**Comment by ramezquitao** [comment]
Regarding the Edmund 45113, I just looked at Edmund webpage, and could not find it. Maybe it is deprecated? If you send me the lens information, I could add it to the lens catalog. For the moment I will close  this issue.

**Comment by hstarmans** [comment]
Ideally there is a bridge between pyoptools and open cascade (core library of freecad) and openscad and pyoptools. I think a lot of the functionality you need is already available in freecad libraries. You should  check out, https://github.com/SolidCode/SolidPython. It is a bridge between openscad and python. There is also a library viewscad. I really like the library though. The tutorial you provided does not work out of the box.. anyhow it is not really an issue, so yes you can close that for now 😉
